<?xml version="1.0" encoding="utf-8"?><Database Name="SportSearch" Class="sportDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=USER\DATABASEDATA;Initial Catalog=SportSearch;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="SportSearchConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.MainSport" Member="MainSport">
    <Type Name="MainSport">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Имя" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Фамилия" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Возраст" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Вес" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="КолТравм" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Соревнование" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>